name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-nodejs-demo:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-nodejs-demo:latest

    - name: Debug secret presence (safe)
      run: |
        echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' && 'yes' || 'no' }}"
        echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' && 'yes' || 'no' }}"

